
# Generated by Django 4.2.1 on 2023-08-11 17:17


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Start Date"),
                ),
                ("end_date", models.DateTimeField(verbose_name="End Date")),
                ("deadline", models.DateTimeField(verbose_name="Deadline")),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.CreateModel(
            name="WorkSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces",
                        to="accounts.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "verbose_name": "WorkSpace",
                "verbose_name_plural": "WorkSpaces",
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Start Date"),
                ),
                ("end_date", models.DateTimeField(verbose_name="End Date")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sprint",
                "verbose_name_plural": "Sprints",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.workspace",
                verbose_name="WorkSpace",
            ),
        ),
    ]
