# Generated by Django 4.2.4 on 2023-08-29 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_team_remove_team_user_and_more'),
        ('projects', '0002_remove_project_deadline_remove_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started At'),
        ),
    ]
